version: '3.8'
services:
  web:
    build: .
    command: gunicorn cfd360.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://avantrades_fmai_user:UoY6slgE6PCXoLfW4RXE7zqSdB4RpklH@dpg-d0bd5fqdbo4c73ckm0h0-a.oregon-postgres.render.com/avantrades_fmai
