version: '3.8'
services:
  web:
    build: .
    command: gunicorn cfd360.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://avantrades_wpxj_user:BAoMh8YgNbzp65RnTdc7UggcQTqDayNi@dpg-d0cu0d6mcj7s73avfj90-a.oregon-postgres.render.com/avantrades_wpxj