# Minimal render.yaml for background worker only
services:
  - type: worker
    runtime: python
    name: investment-updater
    plan: free
    command: python manage.py update_investments --continuous
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: cfd360.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: postgres://user:pass@host:port/dbname  # Replace with your actual DB URL
      - key: UPDATE_INTERVAL_HOURS
        value: "24"  # Runs daily
      # Add other required environment variables

