services:
  - name: avantrades-api
    type: web
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    healthCheckPath: /
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: cfd360.settings
      - key: SECRET_KEY
        value: django-insecure-@+4blrcpti^@m@%&xg+ec*zifp$hip9q0y&4u5!f3efor$050m
      - key: ALLOWED_HOSTS
        value: avantrades-api.onrender.com


  - type: worker
    runtime: python
    name: avantrades-api-worker
    plan: free
    command: python manage.py update_investments --continuous
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: cfd360.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: postgres://postgresql://avantrades_wpxj_user:BAoMh8YgNbzp65RnTdc7UggcQTqDayNi@dpg-d0cu0d6mcj7s73avfj90-a.oregon-postgres.render.com/avantrades_wpxj  # Replace with your actual DB URL
      - key: UPDATE_INTERVAL_HOURS
        value: "24"  # Runs daily
      # Add other required environment variables

