# Generated by Django 3.2.5 on 2023-02-26 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='verification_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Verified', 'Verified')], default='Pending', max_length=250, null=True),
        ),
    ]
