# Generated by Django 4.2 on 2025-04-24 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallets',
            name='deposit',
        ),
        migrations.RemoveField(
            model_name='wallets',
            name='withdrawals',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateTimeField(blank=True, max_length=250, null=True),
        ),
    ]
