# Generated by Django 4.2 on 2025-04-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallets',
            name='address',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
