# Generated by Django 4.2 on 2025-04-24 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_wallets_deposit_remove_wallets_withdrawals_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallets',
            name='user',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='wallets',
            name='email',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
